name: Build library
on:
  push:
    branches:
      - dev
jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v
        with:
          node-version: 16.14.x
      - name: Install dependencies
				run: npm install
			- name: Build package
				run: npm build
