name: Build library
on:
  push:
    branches:
      - dev
jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.x
      - name: Install dependencies anb build library
				run: |
          npm install
          npm run build
