name: Build docs
on:
  push:
    branches:
      - dev
jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.x
      - name: Install docs dependencies
        working-directory: ./docs
        run: npm install
      - name: Build docs
        working-directory: ./docs
        run: npm run build
