name: Build library
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.x
		- name: Install dependencies and build 🔧
		- run: npm install
    - run: npm run build
    - run: npm test