name: Build docs
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install docs dependencies
        run: npm install
      - name: Build docs
        run: cd docs && npm run build
