name: Publish Packages to NPM
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.16.0'
          registry-url: 'https://registry.npmjs.org'
          scope: '@leux'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build:all # ou o build específico para workspaces

      - name: Publish each workspace
        run: |
          for pkg in $(ls -d src/packages/*/); do
            cd $pkg
            echo "Publishing $pkg..."
            npm publish --access public || echo "Skipping already published $pkg"
            cd - > /dev/null
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
