name: Run tests

on:
	pull_request:
		branches:
			- main
			- dev

jobs:
	build:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout
				uses: actions/checkout@v2
			- name: Setup Node
				uses: actions/setup-node@v2
				with:
					node-version: '14.17.3'
					registry-url: 'https://registry.npmjs.org'
			- name: Test all components
				run: npm run test